### ISSUE TITLE
UID received by EnumerateCallback contains empty characters

### ISSUE THREAD

**Issue by martinscheffler** [Tinkerforge/go-api-bindings#1]
The UID passed to EnumerateCallback has a length of eight characters. First three chars are the UID, then 5 empty chars. When I pass the unmodified UID to accelerometer_bricklet.New() I get error "UID contained an invalid character at position: 0"

**Comment by rtrbt** [comment]
Hi, sorry for the late response. This has been fixed in version 2.0.3.
